### ISSUE TITLE
not able to connect HLS-LFOM1 to windows 11

### ISSUE THREAD

**Issue by sidh1603** [HLDS-GIT/hls_lfom_tof_driver#2]
Hi, I have connected the device to ethernet , but when i am checking the ip address its not showing.

**Comment by JeehoonYang** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you for your interest in our products.Unless it's about ros driver, Please contact us using the representative email of the place of purchase.---- 원본 메일 ----보낸 사람 : ***@***.***>받는 사람 : ***@***.***>참조 : ***@***.***>날짜 : 23.04.02 11:54 GMT +0900제목 : [HLDS-GIT/hls_lfom_tof_driver] not able to connect HLS-LFOM1 to windows 11 (Issue #2)
Hi, I have connected the device to ethernet , but when i am checking the ip address its not showing.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/HLDS-GIT/hls_lfom_tof_driver/issues/2",
"url": "https://github.com/HLDS-GIT/hls_lfom_tof_driver/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by HLDS-GIT** [comment]
Please contact us through the product homepage about general issue.

**Comment by HLDS-GIT** [comment]
close issue
